#pragma once
#include "common/framework.h"
#include "common/path.h"
#include "common/zip_entry.h"
#include "common/object.h"
#include "common/worker_thread.h"
#include "common/format.h"
#include "common/code.h"
#include "common/stream.h"
#include "common/const_string.h"
#include "common/logs.h"
#include "common/runnable.h"
#include "common/environment.h"
#include "common/convert.h"
#include "common/mimedata.h"
#include "common/elementparser.h"
#include "common/alias.h"
#include "common/serialization.h"
#include "common/string.h"
#include "common/file.h"
#include "common/algorithm.h"
#include "common/point.h"
#include "common/rect.h"
#include "common/image.h"
#include "common/xmldocument.h"
#include "common/xmlattribute.h"
#include "common/xmlnode.h"
#include "common/directoryentry.h"
#include "common/directoryiterator.h"
#include "common/wobjectdefs.h"

using namespace shelllet::common;


#define DELVELOP_CODE_NAME "Velkhana"